CC_OPTIONS = -Wmissing-declarations -Wno-unused-function -Wunused-parameter -Wno-stringop-truncation -Wno-unused-variable
CC = gcc -O3 -g -Wall $(CC_OPTIONS)
CC_DBG = gcc -O0 -g -pg -Wall $(CC_OPTIONS)
LM = -lm

srcs = $(wildcard *.c)
bins = $(patsubst %.c, %.exe, $(srcs))
bins_dbg = $(patsubst %.c, %_d.exe, $(srcs))
dep_srcs =
deps = $(dep_srcs) \
       $(wildcard *.h) \
       $(wildcard ../../../core/at/*.h) \
       $(wildcard ../../../core/at/*/*.h) \
       $(wildcard ../../../core/at/*/*/*.h) \
       $(wildcard ../../../core/at/*/*/*/*.h) \
       $(wildcard ../../../core/at/*/*/*/*/*.h) \
       Makefile
includes = -I../../../core \
           -I../../../external

bins: $(bins)

$(bins): %.exe : %.c $(deps)
	$(CC) $(includes) $< $(dep_srcs) -o $@ $(LM)

$(bins_dbg): %_d.exe : %.c $(deps)
	$(CC_DBG) $(includes) $< $(dep_srcs) -o $@ $(LM)

clean::
	$(RM) -rf $(bins) $(bins_dbg) *-init.dat .*.swp *~ hist*.bin *manifest* HMB* MTSEED* mb*.dat ZE* ze.dat *_hist*.dat TRACE* trace.dat gmon.out rng*.dat langevin-*.dat data/* atdata*
